version: "3.7"
services:
  openelis:
    profiles: ["default","openelis"]
    image: "bahmni/openelis:${OPENELIS_IMAGE_TAG:?[ERROR]}"
    ports:
      - "8052:8052"
    volumes:
      - "${OPENELIS_MIGRATION_XML_SCRIPTS_PATH}:/var/www/bahmni_config/openelis/migrations"
    environment:
      OPENMRS_HOST: ${OPENMRS_HOST}
      OPENELIS_DB_SERVER: ${OPENELIS_DB_SERVER}
    depends_on:
      openelisdb:
        condition: service_healthy

  openelisdb:
    profiles: ["default","openelis"]
    image: "bahmni/openelis-db:${OPENELIS_DB_IMAGE_TAG:?[ERROR]}"
    ports:
      - "5432:5432"
    volumes:
      - "${OPENELIS_DB_DUMP_PATH}:/resources/db-dump"
      - "openelisdbdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  odoo:
    profiles: ["default","odoo"]
    image: "bahmni/odoo-10:${ODOO_IMAGE_TAG:?[ERROR]}"
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    volumes:
      - odooappdata:/var/lib/odoo
      - ${EXTRA_ADDONS_PATH}:/mnt/extra-addons
      # Uncomment the below volume only when you need to modify existing bahmni-addons. Also make sure to update the .env file variable with odoo-modules github repo cloned path.
      # - ${BAHMNI_ODOO_MODULES_PATH}:/opt/bahmni-erp/bahmni-addons

    depends_on:
      odoodb:
        condition: service_healthy
    environment:
      - HOST=odoodb
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}

  odoodb:
    profiles: ["default","odoo"]
    image: "bahmni/odoo-10-db:${ODOO_DB_IMAGE_TAG:?[ERROR]}"
    ports:
      - "5431:5432"
    volumes:
      - "${ODOO_DB_DUMP_PATH}:/resources/db-dump"
      - "odoodbdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U odoo"]
      interval: 10s
      timeout: 5s
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
      - POSTGRES_USER=${ODOO_DB_USER}

  odoo-connect:
    profiles: ["default","odoo"]
    image: "bahmni/odoo-connect:${ODOO_CONNECT_IMAGE_TAG:?[ERROR]}"
    environment:
      - ODOO_DB_SERVER=odoodb
      - ODOO_DB_USERNAME=${ODOO_DB_USER:?}
      - ODOO_DB_PASSWORD=${ODOO_DB_PASSWORD:?}
      - OPENMRS_HOST=${OPENMRS_HOST:?}
      - OPENELIS_HOST=${OPENELIS_HOST:?}
    depends_on:
      odoodb:
        condition: service_healthy

  openmrs:
    profiles: ["default","openmrs"]
    image: bahmni/openmrs:${OPENMRS_IMAGE_TAG:?}
    environment:
      DB_DATABASE: ${OPENMRS_DB_NAME:?}
      DB_HOST: ${OPENMRS_DB_HOST:?}
      DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      DB_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      DB_AUTO_UPDATE: ${OPENMRS_DB_AUTO_UPDATE}
      MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      DEBUG: ${OPENMRS_DEBUG}
      OPENELIS_HOST: ${OPENELIS_HOST}
    ports:
      - "8080:8080"
    depends_on:
      - openmrsdb

  openmrsdb:
    image: bahmni/openmrs-db:${OPENMRS_DB_IMAGE_TAG:?}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${OPENMRS_DB_NAME:?}
      MYSQL_USER: ${OPENMRS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
    ports:
      - "3306:3306"

volumes:
  openelisdbdata:
  odoodbdata:
  odooappdata:
