name: Build and Publish atomfeed-console
on:
  push:
    branches: [BAH-2139]
    paths:
      - 'atomfeed-console/**'
      - '.github/workflows/atomfeed_console_build_publish.yml'
jobs:
  build-atomfeed-console:
    name: Build atomfeed-console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout atomfeed-console repo
        uses: actions/checkout@v3
        with:
          repository: ICT4H/atomfeed-console
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      # - name: Run Unit Tests
      #   run: mvn --no-transfer-progress clean test
      - name: Install bower
        run: npm install -g bower 
      - name: Package
        run: mvn --no-transfer-progress clean package -DskipTests
      - uses: actions/upload-artifact@v2
        with:
          name: atomfeed-console-SNAPSHOT.jar
          path: target/*.jar

  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    needs: build-atomfeed-console
    steps:
      - uses: actions/checkout@v2
      - name: Verify app version
        run: |
          APP_VERSION=$(cat atomfeed-console/.appversion)
          if [ $(git tag -l "$APP_VERSION") ]; then 
            echo "App version $APP_VERSION already released. Please update app version in package/.appversion to represent next major/minor/patch increment"
            exit 1
          else
            echo "setting artifact version to $(echo $APP_VERSION-${{github.run_number}})"
            echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
          fi
      - name: Download atomfeed-console jar
        uses: actions/download-artifact@v2
        with:
          name: atomfeed-console-SNAPSHOT.jar
          path: atomfeed-console/resources/
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: atomfeed-console/
          no-cache: true
          push: true
          tags: bahmni/atomfeed-console:${{env.ARTIFACT_VERSION}},bahmni/atomfeed-console:latest
          