name: Continuous Integration-v0.94
on:
  push:
    branches:
      - master
env:
  ORG_NAME: mohan-13
  EVENT_TYPE: bahmni-package-0.94-trigger
jobs:
  demo:
    name: Trigger Workflows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repos: ["openerp-atomfeed-service"]
    steps:
      - name: Create repository_dispatch
        env:
          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
        run : |
              curl -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"${EVENT_TYPE}"}'
